# Blunderbuss config

assign_issues:
  - daniel-sanche

assign_issues_by:
  - labels:
      - "samples"
    to:
      - googleapis/python-samples-reviewers

assign_prs:
  - googleapis/api-firestore
  - googleapis/api-firestore-partners
