# Rules for main branch protection
branchProtectionRules:
# Identifies the protection rule pattern. Name of the branch to be protected.
# Defaults to `main`
- pattern: main
  # Can admins overwrite branch protection.
  # Defaults to `true`
  isAdminEnforced: true
  # Number of approving reviews required to update matching branches.
  # Defaults to `1`
  requiredApprovingReviewCount: 1
  # Are reviews from code owners required to update matching branches.
  # Defaults to `false`
  requiresCodeOwnerReviews: true
  # Require up to date branches
  requiresStrictStatusChecks: false
  # List of required status check contexts that must pass for commits to be accepted to matching branches.
  requiredStatusCheckContexts:
    - 'Kokoro'
    - 'Kokoro system-3.8'
    - 'cla/google'
# List of explicit permissions to add (additive only)
permissionRules:
    # Team slug to add to repository permissions
  - team: yoshi-admins
    # Access level required, one of push|pull|admin|maintain|triage
    permission: admin
    # Team slug to add to repository permissions
  - team: yoshi-python-admins
    # Access level required, one of push|pull|admin|maintain|triage
    permission: admin
      # Team slug to add to repository permissions
  - team: yoshi-python
    # Access level required, one of push|pull|admin|maintain|triage
    permission: push
