name: Python-pre-releases

on:
  pull_request:
  schedule:
    # Run daily at midnight
    - cron:  '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    name: Run tests on python pre-release
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.0-alpha - 3.10.0'

      # Run unit tests on pre-release python
      - run: python -m pip install --upgrade setuptools nox
      - run: nox -s unit-3.10
